/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Metrics */
        get: operations["latest_metrics_instruments__symbol__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics Series */
        get: operations["metrics_series_instruments__symbol__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument Signals */
        get: operations["instrument_signals_instruments__symbol__signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Option Chain */
        get: operations["option_chain_instruments__symbol__chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_instruments__symbol__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{symbol}/insights:generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Insight */
        post: operations["generate_insight_instruments__symbol__insights_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_me_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_me_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/watchlist/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_me_watchlist__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChainRow */
        ChainRow: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Instrument Id */
            instrument_id: number;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Strike */
            strike: number;
            /** Underlying */
            underlying?: number | null;
            /** Ce Oi */
            ce_oi?: number | null;
            /** Ce Oi Change */
            ce_oi_change?: number | null;
            /** Ce Iv */
            ce_iv?: number | null;
            /** Ce Ltp */
            ce_ltp?: number | null;
            /** Ce Volume */
            ce_volume?: number | null;
            /** Pe Oi */
            pe_oi?: number | null;
            /** Pe Oi Change */
            pe_oi_change?: number | null;
            /** Pe Iv */
            pe_iv?: number | null;
            /** Pe Ltp */
            pe_ltp?: number | null;
            /** Pe Volume */
            pe_volume?: number | null;
            /**
             * Source
             * @default nse
             */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
        };
        /** Insight */
        Insight: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Instrument Id */
            instrument_id: number;
            /** Expiry */
            expiry?: string | null;
            /** Title */
            title: string;
            /** Narrative */
            narrative: string;
            /** Sentiment Label */
            sentiment_label?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Cited Metrics */
            cited_metrics?: unknown;
            /** Model */
            model?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** Instrument */
        Instrument: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Segment */
            segment?: string | null;
            /** Lot Size */
            lot_size?: number | null;
            /** Tick Size */
            tick_size?: number | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** LatestMetricsResponse */
        LatestMetricsResponse: {
            metrics: components["schemas"]["MetricsRow"];
            summary: components["schemas"]["LatestSummary"];
        };
        /** LatestSummary */
        LatestSummary: {
            /** Underlying */
            underlying?: number | null;
            /** Atm Strike */
            atm_strike?: number | null;
            /** Top Ce Oi */
            top_ce_oi?: components["schemas"]["TopOiStrike"][];
            /** Top Pe Oi */
            top_pe_oi?: components["schemas"]["TopOiStrike"][];
        };
        /** MetricsRow */
        MetricsRow: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Instrument Id */
            instrument_id: number;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Dte */
            dte?: number | null;
            /** Underlying */
            underlying?: number | null;
            /** Pcr Oi */
            pcr_oi?: number | null;
            /** Pcr Volume */
            pcr_volume?: number | null;
            /** Ce Cog */
            ce_cog?: number | null;
            /** Pe Cog */
            pe_cog?: number | null;
            /** Cog Shift */
            cog_shift?: number | null;
            /** Atm Strike */
            atm_strike?: number | null;
            /** Atm Iv */
            atm_iv?: number | null;
            /** Iv Skew */
            iv_skew?: number | null;
            /** India Vix */
            india_vix?: number | null;
            /** Atm Straddle */
            atm_straddle?: number | null;
            /** Expected Move */
            expected_move?: number | null;
            /** Max Pain */
            max_pain?: number | null;
            /** Total Ce Oi */
            total_ce_oi?: number | null;
            /** Total Pe Oi */
            total_pe_oi?: number | null;
            /** Net Ce Oi Change */
            net_ce_oi_change?: number | null;
            /** Net Pe Oi Change */
            net_pe_oi_change?: number | null;
            /** Total Ce Volume */
            total_ce_volume?: number | null;
            /** Total Pe Volume */
            total_pe_volume?: number | null;
            /** Buy Sell Imbalance */
            buy_sell_imbalance?: number | null;
            /** Buildup */
            buildup?: string | null;
            /** Immediate Support */
            immediate_support?: number | null;
            /** Major Support */
            major_support?: number | null;
            /** Immediate Resistance */
            immediate_resistance?: number | null;
            /** Major Resistance */
            major_resistance?: number | null;
            /** Sentiment Score */
            sentiment_score?: number | null;
            /** Sentiment Label */
            sentiment_label?: string | null;
            /** Drivers */
            drivers?: unknown[];
        };
        /** SignalCard */
        SignalCard: {
            /** Key */
            key: string;
            /**
             * Category
             * @enum {string}
             */
            category: "bias" | "levels" | "flow" | "structure" | "volatility";
            /** Title */
            title: string;
            /** Text */
            text: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "bullish" | "bearish" | "neutral";
            /** Strength */
            strength: number;
            /** Evidence */
            evidence?: Record<string, never>;
        };
        /** SignalsResponse */
        SignalsResponse: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Underlying */
            underlying?: number | null;
            overall: components["schemas"]["SignalCard"];
            /** Signals */
            signals: components["schemas"]["SignalCard"][];
        };
        /** TopOiStrike */
        TopOiStrike: {
            /** Strike */
            strike: number;
            /** Oi */
            oi: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistAddRequest */
        WatchlistAddRequest: {
            /** Symbol */
            symbol: string;
        };
        /** WatchlistEntry */
        WatchlistEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Id */
            instrument_id: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_instruments_instruments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"][];
                };
            };
        };
    };
    latest_metrics_instruments__symbol__latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_series_instruments__symbol__metrics_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                fields?: string[] | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instrument_signals_instruments__symbol__signals_get: {
        parameters: {
            query?: {
                at?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    option_chain_instruments__symbol__chain_get: {
        parameters: {
            query?: {
                at?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_instruments__symbol__insights_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insight"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_insight_instruments__symbol__insights_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_me_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntry"][];
                };
            };
        };
    };
    add_to_watchlist_me_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_me_watchlist__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
